data:extend {
    {
        type = "double-setting",
        name = "reactive-evolution-factor-pollution-factor",
        setting_type = "startup",
        default_value = 0.0000009,
        maximum_value = 1,
        minimum_value = 0,
        order = "1",
    },
    {
        type = "bool-setting",
        name = "reactive-evolution-factor-standardize-reduction-factor",
        setting_type = "runtime-global",
        default_value = false,
        order = "1",
    },
    {
        type = "double-setting",
        name = "reactive-evolution-factor-standard-reduction-factor",
        setting_type = "runtime-global",
        default_value = 0.002,
        maximum_value = 1,
        minimum_value = 0,
        order = "2",
    },
    {
        type = "bool-setting",
        name = "reactive-evolution-factor-aliens-gear-for-war",
        setting_type = "runtime-global",
        default_value = false,
        order = "5",
    },
    {
        type = "bool-setting",
        name = "reactive-evolution-factor-enable-debug",
        setting_type = "runtime-global",
        default_value = false,
        order = "6",
    },
    {
        type = "int-setting",
        name = "reactive-evolution-factor-reduction-factor",
        setting_type = "runtime-global",
        default_value = 100,
        maximum_value = 2000,
        minimum_value = 0,
        order = "7",
    },
    {
        type = "double-setting",
        name = "reactive-evolution-factor-evolution-increment-factor",
        setting_type = "runtime-global",
        --default_value = 0.000003,
        default_value = 0.3,
        maximum_value = 1,
        minimum_value = 0,
        hidden = true,
    },
    {
        type = "double-setting",
        name = "reactive-evolution-factor-minimum-evolution-factor",
        setting_type = "runtime-global",
        default_value = 0.0,
        maximum_value = 1.0,
        minimum_value = 0.0,
        hidden = true,
    },
}